### ISSUE TITLE
Lenovo K31-t3 Issue

### ISSUE THREAD

**Issue by TingyiChen** [lenovo-Kraft-T/proprietary_vendor_wingtech#2]
Camera doesn't work.Hope to fix it.

**Comment by dev-harsh1998** [comment]
@TingyiChen link me to ur device tree

**Comment by TingyiChen** [comment]
@dev-harsh1998 K31-t3 can flash K30-T's rom,but it seems that there isn't some camera drivers.I can only give you the offical rom of k31-t3.

**Comment by dev-harsh1998** [comment]
give link i will make patch

**Comment by dev-harsh1998** [comment]
according to your rom :+1:

**Comment by TingyiChen** [comment]
Please wait for about 15 minutes,I will give you the latest offical rom.But the offical rom's version is 5.0.2 and it's 32bit.I am afraid that we can't get the drivers we needed.

**Comment by dev-harsh1998** [comment]
Not official rom cm rom

**Comment by dev-harsh1998** [comment]
give me the link of cm rom you built i will give you the patch for it i dont need the official rom

**Comment by TingyiChen** [comment]
http://pan.baidu.com/s/1o8plIOE.This is the rom,but it's not built by me.I am working out of it.Thanks

**Comment by TingyiChen** [comment]
http://pan.baidu.com/s/1o8plIOE This is the rom,but it's not built by me.I am working out of it.Thanks

**Comment by dev-harsh1998** [comment]
Ok flash this zip in the recovery i have modded some libs from the stock rom this should fix the bug now test it and report weather camera is working fine after it ?

**Comment by TingyiChen** [comment]
ok

**Comment by dev-harsh1998** [comment]
i am uploading, Flash the zip over rom .if it works then i will update the vendor file aswell

**Comment by TingyiChen** [comment]
ok.I am building cm14 now.Thanks.

**Comment by dev-harsh1998** [comment]
http://tx2.androidfilehost.com/dl/sHLi5PheaolEs3-4tMQpTQ/1475637196/24651429356503403/cm13patch1.zip

^^^ DOWNLOAD FROM HERE ^^^

**Comment by dev-harsh1998** [comment]
it will fix camera on your sabermod rom :)

**Comment by TingyiChen** [comment]
ok.i am downloading.

**Comment by TingyiChen** [comment]
I flashed it.Now it's booting.

**Comment by dev-harsh1998** [comment]
Cam Fixed ?

**Comment by TingyiChen** [comment]
Yes.But the original camera disappeared.

**Comment by dev-harsh1998** [comment]
So issue gone now Actually k30 has problem with new m blobs which are fixed by these so is your bug Done ?

**Comment by TingyiChen** [comment]
Yes.But I can only use third-party camera app now.This is the only problem now.

**Comment by dev-harsh1998** [comment]
i will fix this too current issue was to solve your camera not work once you are done with cm 14 link the cm c14 rom to me i will make stock N blobs that will fix the stock cm14 cam :) once you are done with cm14 ping me

**Comment by TingyiChen** [comment]
ok.but maybe i can't finish it...But i will try my best.:)

**Comment by dev-harsh1998** [comment]
@TingyiChen Listen Use my kernel for android n other kernel not work

**Comment by dev-harsh1998** [comment]
https://github.com/dev-harsh1998/android-kernel-wingtech-wt86518

LINK BUT BE SURE TO GIVE PROPER CREDITS

**Comment by TingyiChen** [comment]
ok.tks.and btw,I created a pr.

**Comment by dev-harsh1998** [comment]
wait i am uploading new Ril Blobs wait sync after15mins

**Comment by TingyiChen** [comment]
ok

**Comment by dev-harsh1998** [comment]
Now Sync :) Its done @TingyiChen  Be sure to ping me when needed you can contact me on telegram @dev_harsh1998 is my username on telegram messaging app

**Comment by TingyiChen** [comment]
ok

**Comment by TingyiChen** [comment]
@dev-harsh1998 Hey,Harsh.I can't use telegram in China,so I have to send message to you here.I found another bug:the microphone is unavailable.I try to fix it but failed.Hope you can help me.Tks.

**Comment by dev-harsh1998** [comment]
Whats the issue dear please explain

**Comment by TingyiChen** [comment]
For example,i am calling my mother.When i tell,she can't hear what i said

**Comment by TingyiChen** [comment]
It seems that the microphone doesn't work.

**Comment by dev-harsh1998** [comment]
ohk I see Microphone Fails to forward voice in which rom btw sudamod or CM14 ?

**Comment by TingyiChen** [comment]
SudaMod

**Comment by TingyiChen** [comment]
Not CM14

**Comment by dev-harsh1998** [comment]
hmm Gimme time I will try to aggrange a possible fix as soon as possible

**Comment by TingyiChen** [comment]
ok.tks.I am compiling cm13 and twrp now

**Comment by dev-harsh1998** [comment]
Once you are done with your Cm13 build please link it to me

**Comment by TingyiChen** [comment]
ok.but this afternoon,i tried to build but an error occured.

**Comment by TingyiChen** [comment]
i don't know if i can build successfully

**Comment by dev-harsh1998** [comment]
@TingyiChen Copy 

libacdb-fts.so
libacdbloader.so
libacdbrtac.so

From stock vendor Replace in your Rom

**Comment by TingyiChen** [comment]
rebooting.wait a minute

**Comment by TingyiChen** [comment]
it still doesn't work

**Comment by TingyiChen** [comment]
maybe i should replace libacdbmapper.so？

**Comment by TingyiChen** [comment]
@dev-harsh1998

**Comment by dev-harsh1998** [comment]
yes and dont forget to Set correct permissions otherwise it wont work

**Comment by TingyiChen** [comment]
i have set.but it still don't work

**Comment by TingyiChen** [comment]
btw,i compiled a twrp recovery,but it can't mount partitions,i think its the problem of fstab.can you help me?here is the tree : https://github.com/TingyiChen/android_device_lenovo_msm8916-twrp

**Comment by dev-harsh1998** [comment]
@TingyiChen Copy

libacdb-fts.so
libacdbloader.so
libacdbrtac.so
libacdbmapper.so

Copy From Stock rom to vendor/lib on your sudamod rom and set permissions 0644 or rw-r-r & reboot

**Comment by dev-harsh1998** [comment]
@TingyiChen add me as a contributer there

**Comment by dev-harsh1998** [comment]
i will Update it

**Comment by TingyiChen** [comment]
ok.wait a minute

**Comment by TingyiChen** [comment]
i sent a invite message to you

**Comment by TingyiChen** [comment]
@dev-harsh1998

**Comment by TingyiChen** [comment]
https://github.com/TingyiChen/android_device_lenovo_msm8916-twrp/invitations @dev-harsh1998

**Comment by dev-harsh1998** [comment]
@TingyiChen compile from here https://github.com/dev-harsh1998/android_device_lenovo_msm8916-twrp/tree/patch-1

**Comment by TingyiChen** [comment]
ok.i will have a try

**Comment by TingyiChen** [comment]
i am compiling

**Comment by dev-harsh1998** [comment]
@TingyiChen  the rom sudamod you compiled is 32bit or 64bit ?

**Comment by TingyiChen** [comment]
64bit

**Comment by dev-harsh1998** [comment]
Please Make 32bit as The processor runs and performs best on 32bit thats why floromu also have removed x64 from the tree itself

**Comment by TingyiChen** [comment]
ok

**Comment by TingyiChen** [comment]
I am using the latest device tree.Is it 32bit?

**Comment by dev-harsh1998** [comment]
Yes Its 32bit as 32bit works best for Lenovo and K30 -t & clones So we removed x64 Code :) i hope you compile a 32bit rom next and have success in 32bit rom :+1:

**Comment by TingyiChen** [comment]
ok.so i think i am compiling a 32bit rom 👍

**Comment by TingyiChen** [comment]
and i think you can delete BOARD_SEPOLICY_UNIONS in BoardConfig.mk

**Comment by TingyiChen** [comment]
There is an error occured....WTF...

**Comment by TingyiChen** [comment]
I compiled the recovery but it still can't work.

**Comment by dev-harsh1998** [comment]
Yes i am sure you are enough talented to solve these mini errors just Link me when you successfully compile a 32bit rom :)

**Comment by TingyiChen** [comment]
But this afternoon i met the same error....and i couldn't find way to solve it...

**Comment by dev-harsh1998** [comment]
in compiling rom or recovery ?

**Comment by TingyiChen** [comment]
rom

**Comment by TingyiChen** [comment]
wait a minute,and i will give you the screenshot

**Comment by dev-harsh1998** [comment]
ASK @Silentlys Then On webio or here he is good guy ask in your Native chineese hope he helps better
:) i am not good at device specific errors

**Comment by TingyiChen** [comment]
he is always offline....I could chat with him seldom...

**Comment by TingyiChen** [comment]
[image](https://raw.githubusercontent.com/tingyichen/images/master/ERROR.png)

**Comment by TingyiChen** [comment]
@dev-harsh1998

**Comment by dev-harsh1998** [comment]
@TingyiChen i am not good in rom departments sadly better ask Deliee , Sitentlys Etc guy i am sorry to let you down but from here you are on your own fixing these errors

**Comment by TingyiChen** [comment]
okay...Have you met these errors while using lenovo-kraft-t/android_device_lenovo_msm8916?

**Comment by dev-harsh1998** [comment]
I dont remember actually my friend Cause i just looked at kernel department my dear hope yo are able to fix then and get a booting Cm13 x32 bit rom for our lenovo a6000

**Comment by TingyiChen** [comment]
ok...i will try my best...

**Comment by dev-harsh1998** [comment]
be the best leave the rest :)

**Comment by TingyiChen** [comment]
ok...i think we should add a twrp.fstab to our recovery tree...the recovery still can't work

**Comment by dev-harsh1998** [comment]
its night here my Friend 1am i am from india Dont mind my mom is scolding me i have to sleep i will look at your Device tree tomorrow morning :)

**Comment by TingyiChen** [comment]
ok...it's 23:42 now in China...Good night :)

**Comment by dev-harsh1998** [comment]
GN :)

**Comment by TingyiChen** [comment]
@dev-harsh1998 Hey,harsh,the tree i built successfully now.The recovery seems work now.Enjoy it. :) I am getting to bed :)

**Comment by TingyiChen** [comment]
@dev-harsh1998 harsh,i have renamed the master branch to cm-13.0,please pay attention to it.
